spring:
  application:
    name: personal-financial-management
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_db
    username: financial_admin
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update